INSERT INTO abcdmetadata
(
  MetadataID,
  DatasetGUID,
  TechnicalContactName,
  TechnicalContactEmail,
  TechnicalContactPhone,
  TechnicalContactAddress,
  ContentContactName,
  ContentContactEmail,
  ContentContactPhone,
  ContentContactAddress,
  OtherProviderUDDI,
  DatasetTitle,
  DatasetDetails,
  DatasetCoverage,
  DatasetURI,
  DatasetIconURI,
  DatasetVersionMajor,
  DatasetCreators,
  DatasetContributors,
  DateCreated,
  DateModified,
  OwnerOrganizationName,
  OwnerOrganizationAbbrev,
  OwnerContactPerson,
  OwnerContactRole,
  OwnerAddress,
  OwnerTelephone,
  OwnerEmail,
  OwnerURI,
  OwnerLogoURI,
  IPRText,
  IPRDetails,
  IPRURI,
  CopyrightText,
  CopyrightDetails,
  CopyrightURI,
  TermsOfUseText,
  TermsOfUseDetails,
  TermsOfUseURI,
  DisclaimersText,
  DisclaimersDetails,
  DisclaimersURI,
  LicenseText,
  LicensesDetails,
  LicenseURI,
  AcknowledgementsText,
  AcknowledgementsDetails,
  AcknowledgementsURI,
  CitationsText,
  CitationsDetails,
  CitationsURI,
  SourceInstitutionID,
  SourceID,
  RecordBasis,
  KindOfUnit
  )

VALUES (
  1,
  'especime',
  'Silvino Guambe',
  'guambejr@gmail.com',
  '+258 xxxx xxx',
  'Bairro Central, Maputo, Moçambique',
  'Silvino Guambe',
  'guambejr@gmail.com',
  NULL,
  'Polana Cimento, Maputo, Moçambique',
  NULL,
  'Especimes',
  'Coleção de Espécimes no Museu de História Natural de Maputo',
  NULL,
  NULL,
  NULL,
  '1.0',
  NULL,
  NULL,
  '2016-12-13 18:39:09',
  '2016-12-13 18:39:33',
  'Museu de Historia Natural de Maputo',
  'MHNM','Silvino Dalela Guambe Junior',
  '',
  'Museu, Maputo, Moçambique',
  '+258 21 XX XX XX',
  NULL,
  NULL,
  NULL,
  'intellectual property rights.',
  NULL,
  NULL,
  'Todos direitos reservados',
  NULL,
  NULL,
  'termos de uso.',
  NULL,
  NULL,
  'disclamer: xxxx. no-responsability for ... xxxx xxx x  xxxx .',
  NULL,
  NULL,
  'under the XXXX license.',
  NULL,
  NULL,
  'Reconhecimento a todos professionais involvidos no processo',
  NULL,
  NULL,
  'citations text.',
  NULL,
  NULL,
  'MHNM',
  'Museu Maputo',
  NULL,
  NULL
  );
