"""added collection.authorship

Revision ID: 0588fa365782
Revises: 3399189cb9cc
Create Date: 2017-06-09 12:45:18.941197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0588fa365782'
down_revision = '3399189cb9cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('authorship', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'authorship')
    # ### end Alembic commands ###
