"""remove latitude_f and longitude_f

Revision ID: 1369735c912f
Revises: 61cb45b11dde
Create Date: 2017-06-13 11:12:57.223176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1369735c912f'
down_revision = '61cb45b11dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'latitude_f')
    op.drop_column('collection', 'longitude_f')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('longitude_f', mysql.DOUBLE(asdecimal=True), nullable=True))
    op.add_column('collection', sa.Column('latitude_f', mysql.DOUBLE(asdecimal=True), nullable=True))
    # ### end Alembic commands ###
