"""empty message

Revision ID: 23ee12e1be41
Revises: 7c7befde6a93
Create Date: 2017-05-17 21:45:29.045785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ee12e1be41'
down_revision = '7c7befde6a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'collection', 'provider', ['provider_id'], ['id'])
    op.add_column('multimedia', sa.Column('provider_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'multimedia', 'collection', ['collection_id'], ['id'])
    op.create_foreign_key(None, 'multimedia', 'provider', ['provider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'multimedia', type_='foreignkey')
    op.drop_constraint(None, 'multimedia', type_='foreignkey')
    op.drop_column('multimedia', 'provider_id')
    op.drop_constraint(None, 'collection', type_='foreignkey')
    # ### end Alembic commands ###
