"""added collection.first_date and collection.first_year

Revision ID: 305166eb3bf1
Revises: b32d8885d2fc
Create Date: 2017-06-08 11:21:10.513416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305166eb3bf1'
down_revision = 'b32d8885d2fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('first_date', sa.Date(), nullable=True))
    op.add_column('collection', sa.Column('first_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'first_year')
    op.drop_column('collection', 'first_date')
    # ### end Alembic commands ###
