"""collection.views default to 0

Revision ID: 30ebb0795a99
Revises: 957fa5cfcd6a
Create Date: 2017-06-02 13:56:46.639932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ebb0795a99'
down_revision = '957fa5cfcd6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('views_1', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'views_1')
    # ### end Alembic commands ###
