"""added Collection.district

Revision ID: 3399189cb9cc
Revises: 305166eb3bf1
Create Date: 2017-06-08 21:36:41.728293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3399189cb9cc'
down_revision = '305166eb3bf1'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('district', sa.String(length=100), nullable=True))
    op.add_column('collection', sa.Column('locality', sa.String(length=100), nullable=True))
    op.add_column('collection', sa.Column('municipality', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'municipality')
    op.drop_column('collection', 'locality')
    op.drop_column('collection', 'district')
    ### end Alembic commands ###
