"""added indexes to collection and provider column

Revision ID: 33c76a0d8986
Revises: 1369735c912f
Create Date: 2017-06-13 12:11:56.046181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33c76a0d8986'
down_revision = '1369735c912f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_collection_first_date'), 'collection', ['first_date'], unique=False)
    op.create_index(op.f('ix_collection_first_year'), 'collection', ['first_year'], unique=False)
    op.create_index(op.f('ix_collection_full_scientific_name'), 'collection', ['full_scientific_name'], unique=False)
    op.create_index(op.f('ix_collection_last_date'), 'collection', ['last_date'], unique=False)
    op.create_index(op.f('ix_collection_last_year'), 'collection', ['last_year'], unique=False)
    op.create_index(op.f('ix_collection_latitude'), 'collection', ['latitude'], unique=False)
    op.create_index(op.f('ix_collection_longitude'), 'collection', ['longitude'], unique=False)
    op.create_index(op.f('ix_collection_province'), 'collection', ['province'], unique=False)
    op.create_index(op.f('ix_multimedia_type'), 'multimedia', ['type'], unique=False)
    op.create_index(op.f('ix_provider_abbreviation'), 'provider', ['abbreviation'], unique=False)
    op.create_index(op.f('ix_provider_name'), 'provider', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_name'), table_name='provider')
    op.drop_index(op.f('ix_provider_abbreviation'), table_name='provider')
    op.drop_index(op.f('ix_multimedia_type'), table_name='multimedia')
    op.drop_index(op.f('ix_collection_province'), table_name='collection')
    op.drop_index(op.f('ix_collection_longitude'), table_name='collection')
    op.drop_index(op.f('ix_collection_latitude'), table_name='collection')
    op.drop_index(op.f('ix_collection_last_year'), table_name='collection')
    op.drop_index(op.f('ix_collection_last_date'), table_name='collection')
    op.drop_index(op.f('ix_collection_full_scientific_name'), table_name='collection')
    op.drop_index(op.f('ix_collection_first_year'), table_name='collection')
    op.drop_index(op.f('ix_collection_first_date'), table_name='collection')
    # ### end Alembic commands ###
