"""added Collection.date and Collection.year

Revision ID: 60e1b9ecfc40
Revises: 6fac44336d9d
Create Date: 2017-06-06 15:32:41.603161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e1b9ecfc40'
down_revision = '6fac44336d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('collection', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'year')
    op.drop_column('collection', 'date')
    # ### end Alembic commands ###
