"""changed latitude_f and longitude_f to latitude and longitude

Revision ID: 61cb45b11dde
Revises: efedb076bd77
Create Date: 2017-06-13 11:00:19.721265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61cb45b11dde'
down_revision = 'efedb076bd77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('latitude', sa.Float(precision=30), nullable=True))
    op.add_column('collection', sa.Column('longitude', sa.Float(precision=30), nullable=True))
    # op.drop_column('collection', 'latitude_f')
    # op.drop_column('collection', 'longitude_f')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('collection', sa.Column('longitude_f', mysql.DOUBLE(asdecimal=True), nullable=True))
    # op.add_column('collection', sa.Column('latitude_f', mysql.DOUBLE(asdecimal=True), nullable=True))
    op.drop_column('collection', 'longitude')
    op.drop_column('collection', 'latitude')
    # ### end Alembic commands ###
