"""added thumbnail on the collection table. performance.

Revision ID: 62cf9338b8c6
Revises: fb18c12d805f
Create Date: 2017-06-17 12:33:50.363376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62cf9338b8c6'
down_revision = 'fb18c12d805f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('thumbnail_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'collection', 'multimedia', ['thumbnail_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collection', type_='foreignkey')
    op.drop_column('collection', 'thumbnail_id')
    # ### end Alembic commands ###
