"""changed latitude and longitude to float(numeric) type

Revision ID: 6ba3e8dc2932
Revises: 0588fa365782
Create Date: 2017-06-12 22:41:49.441120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ba3e8dc2932'
down_revision = '0588fa365782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'authorship')
    op.drop_column('collection', 'aquisition_address')
    op.drop_column('collection', 'district')
    op.drop_column('collection', 'locality')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('locality', mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=100), nullable=True))
    op.add_column('collection', sa.Column('district', mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=100), nullable=True))
    op.add_column('collection', sa.Column('aquisition_address', mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=100), nullable=True))
    op.add_column('collection', sa.Column('authorship', mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=100), nullable=True))
    # ### end Alembic commands ###
