"""added district, municipality, back

Revision ID: 7ef285d28230
Revises: 6ba3e8dc2932
Create Date: 2017-06-12 22:42:41.768002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef285d28230'
down_revision = '6ba3e8dc2932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('authorship', sa.String(length=100), nullable=True))
    op.add_column('collection', sa.Column('district', sa.String(length=100), nullable=True))
    op.add_column('collection', sa.Column('locality', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'locality')
    op.drop_column('collection', 'district')
    op.drop_column('collection', 'authorship')
    # ### end Alembic commands ###
