"""added views field on collection

Revision ID: a9307f9bbab6
Revises: ee6f46826015
Create Date: 2017-05-31 14:36:38.770432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9307f9bbab6'
down_revision = 'ee6f46826015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'views')
    # ### end Alembic commands ###
