"""changed the column names year to last_year. added first year

Revision ID: b32d8885d2fc
Revises: 60e1b9ecfc40
Create Date: 2017-06-07 17:35:58.333285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b32d8885d2fc'
down_revision = '60e1b9ecfc40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('last_date', sa.Date(), nullable=True))
    op.add_column('collection', sa.Column('last_year', sa.Integer(), nullable=True))
    op.drop_column('collection', 'date')
    op.drop_column('collection', 'year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('year', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('collection', sa.Column('date', sa.DATE(), nullable=True))
    op.drop_column('collection', 'last_year')
    op.drop_column('collection', 'last_date')
    # ### end Alembic commands ###
