"""added temporary latitude and longitide with float type

Revision ID: c6411bef4d70
Revises: d6c3a08d5976
Create Date: 2017-06-12 23:00:37.300838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6411bef4d70'
down_revision = 'd6c3a08d5976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('longitude', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'longitude')
    # ### end Alembic commands ###
