"""added Collection.unit_id_numeric

Revision ID: d0bba2df6424
Revises: 1f39c8e8d787
Create Date: 2017-06-18 23:59:32.870132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0bba2df6424'
down_revision = '1f39c8e8d787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('unit_id_numeric', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'unit_id_numeric')
    # ### end Alembic commands ###
