"""changed the multimedia name to short_name, and full_name

Revision ID: d2706f2af0cf
Revises: a9307f9bbab6
Create Date: 2017-06-01 16:04:37.651633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2706f2af0cf'
down_revision = 'a9307f9bbab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('multimedia', sa.Column('full_name', sa.String(length=50), nullable=True))
    op.add_column('multimedia', sa.Column('short_name', sa.String(length=50), nullable=True))
    op.drop_column('multimedia', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('multimedia', sa.Column('name', mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=50), nullable=True))
    op.drop_column('multimedia', 'short_name')
    op.drop_column('multimedia', 'full_name')
    # ### end Alembic commands ###
