"""added temporary latitude and longitide with float type

Revision ID: d6c3a08d5976
Revises: 7ef285d28230
Create Date: 2017-06-12 22:44:17.862686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6c3a08d5976'
down_revision = '7ef285d28230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('latitude_f', sa.Float(precision=30), nullable=True))
    op.add_column('collection', sa.Column('longitude_f', sa.Float(precision=30), nullable=True))
    op.drop_column('collection', 'longitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('longitude', mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=30), nullable=True))
    op.drop_column('collection', 'longitude_f')
    op.drop_column('collection', 'latitude_f')
    # ### end Alembic commands ###
