"""added province

Revision ID: ee6f46826015
Revises: b179e7813137
Create Date: 2017-05-26 12:47:02.315595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee6f46826015'
down_revision = 'b179e7813137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('province', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'province')
    # ### end Alembic commands ###
