"""removed the latitude and longitude strings from the collection model

Revision ID: efedb076bd77
Revises: c6411bef4d70
Create Date: 2017-06-13 10:56:58.055284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'efedb076bd77'
down_revision = 'c6411bef4d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'latitude')
    op.drop_column('collection', 'longitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('longitude', mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=30), nullable=True))
    op.add_column('collection', sa.Column('latitude', mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=30), nullable=True))
    # ### end Alembic commands ###
